Meteko:
  ImageResizer:
    # You are able to use the same configuration parameters as for Thumbnail presets configuration https://neos-media.readthedocs.io/en/latest/ThumbnailPresets.htm
    configuration: { }
#      maximumWidth: 1024
#      maximumHeight: 800